global:
  message: Welcome to global microservice environment
loggin:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
